name = "TSPSolver"
uuid = "1bb0ef61-54ec-4182-894e-db986df6f2ff"
authors = ["Ole Kröger <ole@zellerfeld.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
